(() => {
  const issues = {
    'enduring-enterprise': ['Aug 2026','AI Strategy · Leadership','The Enduring Enterprise: Building Systems That Learn With You','How brand, data, process, training, and governance become one adaptive operating system.'],
    'digital-hospitality': ['Jul 2026','AI Agents · Customer Experience','Aurelius and the Future of Digital Hospitality','Designing AI-assisted discovery that is consentful, useful, and unmistakably human-led.'],
    'prompt-to-product': ['Jun 2026','AI Tools Development · Product Strategy','From Prompt to Product: When Custom AI Development Makes Sense','The threshold between a useful off-the-shelf tool and a durable custom capability.'],
    'content-system': ['May 2026','Content Strategy · AI Content','The AI Content System: Editorial Quality at Scale','Source standards, review gates, asset direction, and a calendar with conviction.'],
    'project-management': ['Apr 2026','Project Management · Operations','Project Management, Rebuilt for the Age of AI','Briefs, dependencies, meeting intelligence, and risk flags—without losing accountable ownership.'],
    'measure-after-live': ['Mar 2026','AI Implementation · Analytics','What to Measure After AI Goes Live','Adoption, completion, exceptions, satisfaction, quality, cost, and escalation—not vanity metrics.'],
    'high-trust-ai': ['Feb 2026','UX · Responsible AI','The Anatomy of a High-Trust AI Experience','Disclosure, user control, source-aware answers, accessible design, and graceful failure states.'],
    'service-business-tools': ['Jan 2026','AI Tools · Service Businesses','AI Tools for Service Businesses: A Practical Field Guide','Grounded applications across intake, knowledge retrieval, proposals, delivery, and client updates.'],
    'automation-not-abdication': ['Dec 2025','Automation · Leadership','Automation Is Not Abdication','Where automation can accelerate coordination—and where authority must remain human.'],
    'modern-concierge': ['Nov 2025','AI Agents · Web Design','The Modern Client Concierge','A premium path from website discovery to qualified conversation and human follow-up.'],
    'responsible-ai-guide': ['Oct 2025','Responsible AI · Governance','The Executive Guide to Responsible AI','A plain-language framework for governance, privacy, measurement, and incident readiness.'],
    'pilots-that-learn': ['Sep 2025','AI Implementation · Change Management','Why AI Pilots Stall—and How to Design One That Learns','Clear owners, useful baselines, feedback loops, and deliberate scope create learning pilots.'],
    'buy-configure-build': ['Aug 2025','AI Tools Development · Procurement','The AI Tool Stack: Buy, Configure, or Build?','A decision guide for commodity software, custom workflows, unique data, and integration depth.'],
    'brand-voice-asset': ['Jul 2025','Brand Strategy · Knowledge Systems','Your Brand Voice Is an Operating Asset','How voice principles and approved language become safe, useful AI working context.'],
    'education-program': ['Jun 2025','AI Education · Corporate Training','Designing an AI Education Program People Will Actually Use','Role-specific learning, office hours, examples, guardrails, and measures beyond attendance.'],
    'boardroom-value': ['May 2025','AI Strategy · Governance','The Boardroom Guide to AI Value','Replace vague ROI promises with a scorecard for time, quality, risk, adoption, and outcomes.'],
    'lead-qualification': ['Apr 2025','AI Agents · Lead Generation','From Inquiry to Intelligence: Reimagining Lead Qualification','A respectful intake journey that discovers needs without pretending to be human.'],
    'prompt-library': ['Mar 2025','Prompt Engineering · Training','The Prompt Library: Your Team’s New Field Manual','Reusable prompts and examples create a higher quality floor for everyday work.'],
    'useful-ai-agent': ['Feb 2025','AI Agents · Product Design','What Makes an AI Agent Useful, Not Just Impressive','Focused instructions, relevant tools, narrow permissions, evaluation, and escalation.'],
    'readiness-sprint': ['Jan 2025','AI Strategy · Roadmaps','The 90-Day AI Readiness Sprint','Discovery, use-case selection, pilot design, team enablement, and measurement in sequence.'],
    'trained-host': ['Dec 2024','Web Design · Conversion','A Website Should Behave Like a Well-Trained Host','Anticipatory service, dignified calls to action, and intelligent handoffs build confidence.'],
    'human-signature': ['Nov 2024','Responsible AI · Customer Experience','The Human Signature in an Automated World','Where high-value human review belongs in sales, service, creative work, and decisions.'],
    'workflow-before-tool': ['Oct 2024','AI Tools · Operations','Build the Workflow Before You Buy the Tool','Map the client or team workflow first; fit technology to the work rather than the other way around.'],
    'prompt-business-writing': ['Sep 2024','Prompt Engineering · AI Education','Prompt Engineering Is the New Business Writing','Context, constraints, examples, acceptance criteria, and review are the new practical brief.'],
    'ai-readiness': ['Aug 2024','AI Strategy · Transformation','The Executive Case for AI Readiness','Before selecting tools, identify the work, information, owners, and risks that matter.']
  };
  const key = new URLSearchParams(location.search).get('issue') || 'enduring-enterprise';
  const issue = issues[key] || issues['enduring-enterprise'];
  const [date, tags, title, dek] = issue;
  document.title = `${title} — Anchor Notes`;
  const body = document.querySelector('#article');
  const sections = [
    ['The question beneath the request', `Every conversation about ${title.toLowerCase()} begins with a request for a tool, a workflow, or a faster answer. The more consequential question is usually quieter: what work is the business trying to protect, improve, or make possible? A useful system does not start with a model demonstration. It starts with a specific moment in which a client, colleague, or leader needs to make a better decision. That moment has a context, an owner, source material, a tolerance for error, and a human consequence. Naming those conditions turns a vague innovation project into a design brief. It also keeps the team from confusing activity with progress. The goal is not to introduce intelligence everywhere. The goal is to make the right part of the operation more capable while preserving the judgment that makes the organization distinctive.`],
    ['Start with the operating reality', `Map the present experience before promising the future one. Follow the work from first signal to finished outcome: who receives the request, where information lives, which handoffs create delay, where interpretation is required, and what happens when the usual path fails. This map should include the work people do around the official process—the clarifying email, the informal check, the spreadsheet no one owns, the call that saves a relationship. Those details are not inefficiency to erase automatically. They are evidence about service, risk, and value. In the context of ${title}, they tell a team where assistance may be welcome and where automation would be careless. Good implementation is less about replacing a sequence than giving a responsible person better context at the moment it matters.`],
    ['Design the decision, not just the interface', `Interfaces are where a system reveals its manners. A polished surface that cannot explain what it knows, what it cannot do, or where a person remains accountable is not a premium experience. For ${title}, define the decision each step supports. Then make the source, confidence, next action, and escalation path visible enough for a real person to use. That may be a concise recommendation with linked evidence; it may be a draft waiting for approval; it may simply be a graceful invitation to bring a specialist into the conversation. The pattern is consistent: the system should reduce avoidable effort without disguising uncertainty. Users trust a service that is clear about its limits far more than one that performs confidence.`],
    ['Give ownership a name', `The fastest way to make an initiative fragile is to make it everyone’s responsibility and no one’s craft. Assign a business owner for the outcome, a steward for the content and knowledge, a technical owner for reliability, and a review owner for consequential exceptions. These roles do not need to be large departments. They do need to be explicit. The team should know who can change instructions, who approves new data sources, who reads feedback, and who decides when a problem is serious enough to pause the experience. This is the practical discipline behind ${title}. It transforms governance from a document written after launch into a working cadence: observe, review, adjust, and communicate.`],
    ['Make learning a feature', `A system becomes useful when people can form accurate expectations about it. That requires training designed around real situations, not a one-time tour of features. Build a small library of representative examples: a straightforward case, an ambiguous case, a sensitive case, and a failure case. Let people practice the language of context, constraints, evidence, and review. Ask what would make them comfortable using the system with a client in the room. Their answers usually reveal more than a generic adoption survey. In the practice of ${title}, the most valuable enablement is specific enough to change tomorrow’s work and modest enough to revise as the work changes. A living playbook outperforms a perfect binder.`],
    ['Measure what deserves to endure', `A launch is the beginning of evidence, not the end of the project. Establish a baseline before change, then measure a balanced set of signals: time to a useful outcome, completion quality, exception rate, user confidence, customer response, operating cost, and the rate at which people choose the new path voluntarily. No single metric carries the whole story. Faster work that creates more corrections is not progress; high usage without comprehension is not adoption. Review qualitative feedback beside the numbers, especially the questions people repeat and the moments they abandon a flow. That is how ${title} becomes a disciplined investment rather than a collection of anecdotes.`],
    ['Protect the human signature', `High-end service is not defined by how invisible people become. It is defined by how intelligently their attention is used. Reserve human judgment for exceptions, relationships, creative direction, and decisions with material consequences. Use technology to prepare, organize, surface patterns, and make the routine more graceful. Tell people when they are interacting with an automated system and give them a dignified path to a person. This is not merely a compliance gesture. It is hospitality. It tells a visitor that the organization values their time enough to be direct, and values the relationship enough to remain accountable. That is the standard Anchor applies to ${title}.`],
    ['A measured next move', `The next move need not be a grand transformation. Choose one consequential journey, name its owner, write the desired outcome, identify the material it can safely use, and decide how a person will review the result. Run it long enough to learn, with a visible route for feedback and a clear condition for stopping. Then share what changed—both the improvement and the limitation—with the people whose work it affects. This is how confidence is earned. ${title} is not a promise that a business can be run on autopilot. It is an invitation to build an operation that learns deliberately, serves more thoughtfully, and keeps its standards intact.`]
    ,['Create a standard of evidence', `The more consequential the use case, the more important it is to distinguish a plausible answer from a dependable one. Decide what evidence is acceptable before a system begins making recommendations. For some work, approved internal documentation and an identified reviewer may be enough. For other work, a current record, a source citation, a second check, or an explicit refusal is essential. Make that standard visible to the people using the system. It changes behavior in a healthy way: colleagues learn not to treat a fluent draft as a finished decision, and leaders learn where investment in better source material will have the greatest return. In ${title}, evidence is not a technical footnote. It is part of the service promise.`]
    ,['Respect the economics of attention', `Every new system asks for attention: from the person who learns it, the manager who monitors it, and the customer who decides whether to trust it. Treat that attention as a finite resource. Remove redundant steps before adding dashboards. Use a small number of clear signals instead of a ceremony of notifications. Give a person an obvious way to recover when the system is wrong or when the situation is unusual. When the work is quiet and capable, people have more room for judgment, craft, and relationship. That is a more meaningful definition of efficiency than speed alone. The design test for ${title} is simple: does it make the next responsible action clearer, or does it merely make the operation louder?`]
    ,['Keep the system revisable', `No operating reality stays still. Policies change, source material ages, a team learns, and a client expectation shifts. Design for revision from the beginning: keep instructions readable, separate content from code where practical, log meaningful exceptions, and schedule a review before small compromises become a permanent pattern. Revision is not a sign that the original work failed; it is evidence that the work is being stewarded. The best teams make improvement ordinary. They return to the brief, compare intent with evidence, and change the system without drama. That posture keeps ${title} grounded in the business it serves instead of frozen in the moment it was launched.`]
  ];
  body.innerHTML = `<p class="article-kicker">Anchor Notes · ${date}</p><h1>${title}</h1><p class="article-dek">${dek}</p><p class="article-meta">${tags} · Long-form editorial</p><div class="article-hero" aria-hidden="true"></div><div class="article-body">${sections.map(([h,p]) => `<h2>${h}</h2><p>${p}</p>`).join('')}<aside class="article-note"><strong>Editorial note.</strong> This archive is maintained as an educational point of view, not legal, security, or financial advice. Apply policies and professional review appropriate to your organization.</aside><section class="article-sources"><h2>Further reading</h2><p><a href="https://www.nist.gov/itl/ai-risk-management-framework" target="_blank" rel="noreferrer">NIST AI Risk Management Framework</a> offers a useful vocabulary for mapping, measuring, managing, and governing AI risk. For accessible interaction standards, consult the <a href="https://www.w3.org/WAI/standards-guidelines/wcag/" target="_blank" rel="noreferrer">W3C Web Content Accessibility Guidelines</a>.</p></section><nav class="article-next" aria-label="Article navigation"><a href="Blog_Page_Heading_Animation.html">← Return to Notes</a><a href="Meet_Aurelius.html">Discuss the work with Aurelius →</a></nav></div>`;
})();
