(() => {
  'use strict';
  const form=document.querySelector('#booking-form'); if(!form)return;
  const date=form.querySelector('[name="date"]'),time=form.querySelector('[name="time"]'),status=document.querySelector('#booking-status'),submit=form.querySelector('[type="submit"]');
  const now=new Date(),isoToday=new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,10); date.min=isoToday;
  const message=(text,kind='')=>{status.textContent=text;status.className=`form-status ${kind}`.trim();};
  const isWeekday=value=>{const day=new Date(`${value}T12:00:00`).getDay();return day>0&&day<6;};
  const refreshTimes=async()=>{time.innerHTML='<option value="">Loading availability…</option>';time.disabled=true;if(!date.value){time.innerHTML='<option value="">Choose a weekday first</option>';return;}if(!isWeekday(date.value)){time.innerHTML='<option value="">Monday–Friday only</option>';message('Please choose a Monday through Friday.','is-error');return;}message('');try{const response=await fetch(`/.netlify/functions/booking-availability?date=${encodeURIComponent(date.value)}`),data=await response.json();if(!response.ok)throw new Error(data.error||'Availability is unavailable.');time.innerHTML='<option value="">Choose a time</option>'+data.slots.map(slot=>`<option value="${slot.value}"${slot.available?'':' disabled'}>${slot.label}${slot.available?'':' — reserved'}</option>`).join('');time.disabled=false;}catch(error){time.innerHTML='<option value="">Availability is temporarily unavailable</option>';message(error.message||'Availability is temporarily unavailable. Please try again.','is-error');}};
  date.addEventListener('change',refreshTimes);
  form.addEventListener('submit',async event=>{event.preventDefault();if(!form.reportValidity())return;if(!isWeekday(date.value)){message('Please choose a Monday through Friday.','is-error');return;}submit.disabled=true;message('Securing your time…');const payload=Object.fromEntries(new FormData(form).entries());try{const response=await fetch('/.netlify/functions/booking',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),data=await response.json();if(!response.ok)throw Object.assign(new Error(data.error||'We could not reserve that time.'),{code:data.code});form.reset();time.innerHTML='<option value="">Choose a weekday first</option>';time.disabled=true;message(`Reserved: ${data.booking.dateLabel} at ${data.booking.timeLabel} Central Time. A confirmation has been sent.`,'is-success');}catch(error){message(error.code==='SLOT_TAKEN'?'That time was just reserved. Please choose another available time.':(error.message||'We could not reserve that time. Please try again.'),'is-error');if(error.code==='SLOT_TAKEN')refreshTimes();}finally{submit.disabled=false;}});
})();
